local icons = {
  h123 = { "󰉫 ", "󰉬 ", "󰉭 ", "󰉮 ", "󰉯 ", "󰉰 " },
  bars = { "▇ ", "▆ ", "▅ ", "▄ ", "▃ ", "▂ " },
  marks = { " ", " ", " ", " ", " ", " " },
  hashs = { " ", " ", " ", " ", " ", " " },
  hashs_partial = { " ", " ", "  ", "  ", "  ", "  " },
  dots = { "· ", "· ", "· ", "· ", "· ", "· " },
  middots = { "◉ ", "• ", "· ", "⁚ ", "⁖ ", "⸬ " }, --, "⁙ " },
  hexa = { "󰫈 ", "󰫇 ", "󰫆 ", "󰫅 ", "󰫄 ", "󰫃 " },
  dice = { "󱅏 ", "󱅎 ", "󱅍 ", "󱅌 ", "󱅋 ", "󱅊 " },
  Dice = { "󰇏 ", "󰇎 ", "󰇍 ", "󰇌 ", "󰇋 ", "󰇊 " },
  circle = { "󰲡 ", "󰲣 ", "󰲥 ", "󰲧 ", "󰲩 ", "󰲫 " },
  Circle = { "󰲠 ", "󰲢 ", "󰲤 ", "󰲦 ", "󰲨 ", "󰲪 " },
  square = { "󰎦 ", "󰎩 ", "󰎬 ", "󰎮 ", "󰎰 ", "󰎵 " },
  Square = { "󰎤 ", "󰎧 ", "󰎪 ", "󰎭 ", "󰎱 ", "󰎳 " },
  digital = { "🯱 ", "🯲 ", "🯳 ", "🯴 ", "🯵 ", "🯶 " },
  roman = { "Ⅰ ", "Ⅱ ", "Ⅲ ", "Ⅳ ", "Ⅴ ", "Ⅵ " },
}

return {
  "MeanderingProgrammer/render-markdown.nvim",
  ft = { "markdown", "codecompanion", "Avante" },
  opts = {
    file_types = { "markdown", "codecompanion", "Avante" },
    heading = {
      sign = true,
      signs = icons.roman,
      position = "inline",
      icons = icons.Square,
    },
    paragraph = { left_margin = 0 },
    bullet = { left_pad = 0 },
    checkbox = { left_pad = 0 },
    pipe_table = { preset = "round" },
    code = {
      position = "right",
      width = "block",
      min_width = 70,
      left_pad = 3,
      right_pad = 1,
      language_right = "█",
      border = "thick",
      inline_pad = 1,
    },
    latex = { enabled = false },
  },
}
